# Generated by Django 3.1.3 on 2020-12-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='time_end',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='record',
            name='time_start',
            field=models.TimeField(default='00:00'),
        ),
    ]
